# Use the Fedora base image
FROM fedora:latest

# Upgrade the system
RUN dnf -y upgrade

# Install the required applications
RUN dnf -y install tuxpaint vim httpd

# Add the myinfo.html file to the container at /var/www/html/
COPY myinfo.html /var/www/html/

# Create the data directory and copy the dummy-content.txt file into it
COPY data/dummy-content.txt /data/

# Expose port 80
EXPOSE 80/TCP

# Start the httpd service
ENTRYPOINT ["/usr/sbin/httpd", "-DFOREGROUND"]
